library practicetext;

import 'dart:html';

String homerow = '''The  This is the anyone at no it this set ISO THE E net Note has an See h n s note in A to In Sense I T No st It a that on his so he as one not she says see Is Oh thing nonsense soon go any into than engage they say They none high these Ah get She its II those He then hat t To Aye Then One Nonsense too gone At III Not Nothing nothing sat ten sight An easy His attention estate again against sit hate sitting eye seen yet going So got ease seeing eyes hasty sense ostentation easiness tenant age On highest St That Yes night ate things nine sees As attentions intention sing saying song taste instant notion noise nothingness Nay ensign nay haste hating te stay getting insist stays hint goes o eat assent anything height netting assistant singing tone inattention sent yes thin sonnet sang songs hints tea Against staying sign ago th se Things estates shine Has state These antagonist notions nothings assents ones noisy hot seats eight season hesitating astonish hates son assist tenants station Anne oh assisting shoe Attention heighten eyeing sensations agonies signs tythes eating hastening insists gaiety Those sooth Soon sheet gets gaieties engaging hesitate hasten agony noon shyness gain gate neatness neat sigh shoes hesitation agitation anti seat senses stating gig Any Yet sons intentions honest Again agitating gates sheets atone inn satin nasty sea gay tens tents tent agitations tastes setting stone Its sings sensation hanging shy nose teeth inns Say notes gaining stage East Ten Stay Haye Into Stone shoot Tis shan hang sash sha nt Go Hate shooting None test Too States ANYTHING THIS entity site e THAT NO THOSE IN ANY NOT TO AS IS states agent non EIN S''';

void practiceText(String contents) {
  var target = document.querySelector('#targettext');
  target.appendText(contents);
}